---
- name: Projeto Korp
  hosts: localhost
  connection: local

  tasks:

    - name: Verificar Docker
      ansible.builtin.command:
        cmd: docker --version
      register: docker_version

    - name: Exibir versao do Docker
      debug:
        var: docker_version.stdout

    - name: Criar rede Docker
      community.docker.docker_network:
        name: korp-network
        state: present

    - name: Build da aplicacao
      ansible.builtin.command:
        cmd: docker compose build
        chdir: "{{ playbook_dir }}/.."

    - name: Subir containers
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: "{{ playbook_dir }}/.."

    - name: Aguardar inicializacao
      pause:
        seconds: 10

    - name: Testar endpoint
      uri:
        url: http://localhost/projeto-korp
        method: GET
        return_content: true
      register: resposta

    - name: Exibir resposta
      debug:
        var: resposta.json

    - name: Testar healthcheck
      uri:
        url: http://localhost/health
        method: GET
        return_content: true
      register: health_response

    - name: Exibir healthcheck
      debug:
        var: health_response.json
      